language: java
jdk:
- oraclejdk8
addons:
  apt:
    sources:
    - mongodb-upstart
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
    - mongodb-org-shell
services:
  - postgresql
  - mysql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- psql -c 'create schema j_some authorization postgres;' -U postgres travis_ci_test
- mysql -e 'create database travis_ci_test;' -u root
script:
- ./gradlew build
- ./gradlew integrationTest
deploy:
  skip_cleanup: true
  provider: script
  script: travis/deployToSonatype.sh
  on:
    tags: true
    all_branches: true
sudo: false

